#!/bin/bash

echo "################################################################"
echo "# 이 스크립트는 현재 호스트의 DB를 슬레이브로 만드는 스크립트입니다."
echo "################################################################"

master_host=$1

if [ -z "$master_host" ]; then
  echo "첫 번째 인자로 master의 호스트가 필요합니다!"
  exit 1;
fi

echo "이 DB를 slave로 구성하기 위해 $master_host의 마스터 정보를 알아 옵니다."
master_log_file=$(mysql --host=$master_host --user=mha --password=mha -Ne "show master status\G" | head -n 2 | tail -n 1)
master_log_pos=$(mysql --host=$master_host --user=mha --password=mha -Ne "show master status\G" | head -n 3 | tail -n 1)

echo "mha 사용자로 로컬호스트 접근은 어렵기 때문에, 이 호스트의 주소를 구합니다."
host=$(ifconfig ens192 | grep 'inet' | head -1 | awk '{print $2}')

echo "이 호스트($host)에서 Slave를 시작합니다."
mysql --host=$host --user=mha --password=mha -e "stop slave;"
mysql --host=$host --user=mha --password=mha -e "change master to master_host='$master_host', master_user='repl', master_password='repl', master_log_file='$master_log_file', master_log_pos=$master_log_pos;"
mysql --host=$host --user=mha --password=mha -e "start slave;"
mysql --host=$host --user=mha --password=mha -e "show slave status\G;"