#!/bin/bash

echo "################################################################"
echo "# 이 스크립트는 MHA 매니저를 시작하는 스크립트입니다."
echo "################################################################"

/usr/local/bin/masterha_manager --conf=/etc/masterha/rms.cnf --last_failover_minute=1 "$@" &